USE [BookStore]
GO

INSERT INTO Books ([Title]) VALUES ('20.000 leguas de viaje submarino')
INSERT INTO Books ([Title]) VALUES ('Frankenstein')
INSERT INTO Books ([Title]) VALUES ('La isla del tesoro')
INSERT INTO Books ([Title]) VALUES ('Colmillo Blanco')
INSERT INTO Books ([Title]) VALUES ('El Principito')
INSERT INTO Books ([Title]) VALUES ('El gran Gatsby')
INSERT INTO Books ([Title]) VALUES ('1984')
INSERT INTO Books ([Title]) VALUES ('Cuento de Navidad')
INSERT INTO Books ([Title]) VALUES ('El diario de Ana Frank')
INSERT INTO Books ([Title]) VALUES ('Trilogía de El señor de los anillos')
INSERT INTO Books ([Title]) VALUES ('Al este del Edén')
INSERT INTO Books ([Title]) VALUES ('Alicia en el País de las Maravillas')
INSERT INTO Books ([Title]) VALUES ('Matar a un ruiseñor')
INSERT INTO Books ([Title]) VALUES ('El señor de las moscas')
INSERT INTO Books ([Title]) VALUES ('Orgullo y prejuicio')
INSERT INTO Books ([Title]) VALUES ('Cumbres borrascosas')
INSERT INTO Books ([Title]) VALUES ('Hamlet')
INSERT INTO Books ([Title]) VALUES ('Don Quijote')
INSERT INTO Books ([Title]) VALUES ('El guardián entre el centeno')
INSERT INTO Books ([Title]) VALUES ('Ulysses')
INSERT INTO Books ([Title]) VALUES ('Anna Karenina')
INSERT INTO Books ([Title]) VALUES ('Un mundo feliz')
INSERT INTO Books ([Title]) VALUES ('Trampa 22')
INSERT INTO Books ([Title]) VALUES ('En el camino')
INSERT INTO Books ([Title]) VALUES ('Los cuentos')
INSERT INTO Books ([Title]) VALUES ('La guerra de los mundos')
INSERT INTO Books ([Title]) VALUES ('Alguien voló sobre el nido del cuco')
INSERT INTO Books ([Title]) VALUES ('Las mil y una noches')
INSERT INTO Books ([Title]) VALUES ('Las cuitas del joven Werther')
INSERT INTO Books ([Title]) VALUES ('Robinson Crusoe')
INSERT INTO Books ([Title]) VALUES ('Los viajes de Gulliver')
INSERT INTO Books ([Title]) VALUES ('Romeo y Julieta')
INSERT INTO Books ([Title]) VALUES ('La Divina Comedia')
INSERT INTO Books ([Title]) VALUES ('Notre Dame de París')
INSERT INTO Books ([Title]) VALUES ('Madame Bovary')
INSERT INTO Books ([Title]) VALUES ('Crimen y castigo')
INSERT INTO Books ([Title]) VALUES ('La metamorfosis')
INSERT INTO Books ([Title]) VALUES ('El viejo y el mar')
INSERT INTO Books ([Title]) VALUES ('Manhattan Transfer')
INSERT INTO Books ([Title]) VALUES ('Las uvas de la ira')
INSERT INTO Books ([Title]) VALUES ('En busca del tiempo perdido')
INSERT INTO Books ([Title]) VALUES ('Las peregrinaciones de Childe Harold')
INSERT INTO Books ([Title]) VALUES ('¿Sueñan los androides con ovejas eléctricas?')
INSERT INTO Books ([Title]) VALUES ('El extraño caso del Dr. Jekyll y Mr. Hyde')
INSERT INTO Books ([Title]) VALUES ('Viaje al centro de la Tierra')
INSERT INTO Books ([Title]) VALUES ('Adiós a las armas')
INSERT INTO Books ([Title]) VALUES ('Juan Salvador Gaviota')
INSERT INTO Books ([Title]) VALUES ('El mago de Oz')
INSERT INTO Books ([Title]) VALUES ('De ratones y hombres')
INSERT INTO Books ([Title]) VALUES ('Sueño de una noche de verano')
INSERT INTO Books ([Title]) VALUES ('Los miserables')
INSERT INTO Books ([Title]) VALUES ('Oliver Twist')
INSERT INTO Books ([Title]) VALUES ('El Lazarillo de Tormes')
INSERT INTO Books ([Title]) VALUES ('La Celestina')
INSERT INTO Books ([Title]) VALUES ('La casa de Bernarda Alba')
INSERT INTO Books ([Title]) VALUES ('El Hobbit')
INSERT INTO Books ([Title]) VALUES ('La historia interminable')
INSERT INTO Books ([Title]) VALUES ('Los cinco')
INSERT INTO Books ([Title]) VALUES ('Saga Harry Potter')
INSERT INTO Books ([Title]) VALUES ('Torres de Malory')
INSERT INTO Books ([Title]) VALUES ('La elegancia del erizo')
INSERT INTO Books ([Title]) VALUES ('Cien años de soledad')
INSERT INTO Books ([Title]) VALUES ('La senda del perdedor')
INSERT INTO Books ([Title]) VALUES ('Leyendas')
INSERT INTO Books ([Title]) VALUES ('Memorias de Idhún')
INSERT INTO Books ([Title]) VALUES ('La vida es sueño')
INSERT INTO Books ([Title]) VALUES ('Bel Ami')
INSERT INTO Books ([Title]) VALUES ('Ilusiones')
INSERT INTO Books ([Title]) VALUES ('Mujercitas')
INSERT INTO Books ([Title]) VALUES ('Marianela')
INSERT INTO Books ([Title]) VALUES ('Platero y yo')
INSERT INTO Books ([Title]) VALUES ('Siddharta')
INSERT INTO Books ([Title]) VALUES ('El Cantar de Mio Cid')
INSERT INTO Books ([Title]) VALUES ('La campana de cristal')
INSERT INTO Books ([Title]) VALUES ('Moby Dick')
INSERT INTO Books ([Title]) VALUES ('David Copperfield')
INSERT INTO Books ([Title]) VALUES ('Crónica de una muerte anunciada')
INSERT INTO Books ([Title]) VALUES ('Historia de una escalera')
INSERT INTO Books ([Title]) VALUES ('Luces de bohemia')
INSERT INTO Books ([Title]) VALUES ('El curioso incidente del perro a medianoche')
INSERT INTO Books ([Title]) VALUES ('Drácula')
INSERT INTO Books ([Title]) VALUES ('Las aventuras de Huckleberry Finn')
INSERT INTO Books ([Title]) VALUES ('Episodios nacionales')
INSERT INTO Books ([Title]) VALUES ('La letra escarlata')
INSERT INTO Books ([Title]) VALUES ('El llano en llamas')
INSERT INTO Books ([Title]) VALUES ('Miedo y asco en Las Vegas')
INSERT INTO Books ([Title]) VALUES ('Entrevista con el vampiro')
INSERT INTO Books ([Title]) VALUES ('Lolita')
INSERT INTO Books ([Title]) VALUES ('La naranja mecánica')
INSERT INTO Books ([Title]) VALUES ('Pippi Calzaslargas')
INSERT INTO Books ([Title]) VALUES ('Rebelión en la granja')
INSERT INTO Books ([Title]) VALUES ('Rojo y negro')
INSERT INTO Books ([Title]) VALUES ('Trainspotting')
INSERT INTO Books ([Title]) VALUES ('La fundación')
INSERT INTO Books ([Title]) VALUES ('Los tres mosqueteros')
INSERT INTO Books ([Title]) VALUES ('La vuelta al mundo en 80 días')
INSERT INTO Books ([Title]) VALUES ('La Metamorfosis')
INSERT INTO Books ([Title]) VALUES ('El sabueso de los Baskerville')
INSERT INTO Books ([Title]) VALUES ('El crepúsculo de los ídolos')
INSERT INTO Books ([Title]) VALUES ('Don Juan Tenorio')